modLoader = "javafml"
loaderVersion = "*"
license = "GPLv3"
issueTrackerURL="https://github.com/anviaan/SodiumExtraInformation/issues"

[[mods]]
modId = "sodiumextrainformation"

version = "${version}"
displayName = "Sodium Extra Information"

logoFile = "sodiumextrainformation.png"

authors = "anvian"

description = '''
A Sodium Extra addon that adds more in-game information.
'''

[[dependencies.sodiumextrainformation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodiumextrainformation]]
modId = "sodium"
type = "required"
versionRange = "[0.8,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodiumextrainformation]]
modId = "sodium_extra"
type = "required"
versionRange = "[0.8,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "sodiumextrainformation.mixins.json"

[[mixins]]
config = "sodiumextrainformation-neoforge.mixin.json"