name: Java CI with Gradle

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build Artifacts - Fabric
        uses: actions/upload-artifact@v4
        with:
          name: 'Sodium Extra Fabric Artifacts'
          path: fabric/build/libs
      - name: Upload Build Artifacts - NeoForge
        uses: actions/upload-artifact@v4
        with:
          name: 'Sodium Extra NeoForge Artifacts'
          path: neoforge/build/libs
