name: Self-Hosted runner CI with Gradle

on: [push]

jobs:
  selfhost-build:
    if: github.repository_owner == 'FlashyReese'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build and Publish with Gradle
        run: ./gradlew build publishAllPublicationsToFlashyReeseSnapshotsRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload Build Artifacts - Fabric
        uses: actions/upload-artifact@v4
        with:
          name: 'Sodium Extra Fabric Artifacts'
          path: fabric/build/libs
      - name: Upload Build Artifacts - NeoForge
        uses: actions/upload-artifact@v4
        with:
          name: 'Sodium Extra NeoForge Artifacts'
          path: neoforge/build/libs
